### ISSUE TITLE
not a valid object name: HEAD

### ISSUE THREAD

**Issue by ksamuel** [David-OConnor/pyflow#123]
Using pyflow 0.3 installed from the .deb file on Ubuntu 20.04, in a fresh pyflow cpython 3.6 venv:

```
╰─ pyflow install ipython -d                 
Found lockfile
⬇ Installing decorator 5.0.9 ...
⬇ Installing matplotlib_inline 0.1.2 ...
⬇ Installing jedi 0.18.0 ...
⬇ Installing wcwidth 0.2.5 ...
⬇ Installing traitlets 5.0.5 ...
thread 'main' panicked at 'running setup.py bdist_wheel in folder "/media/user/209A5FB6128B7458/Work/projets_dev/filematch/repo/__pypackages__/3.6/lib/traitlets-5.0.5". Py path: "/media/user/209A5FB6128B7458/Work/projets_dev/filematch/repo/__pypackages__/3.6/.venv/bin/python": fatal: not a valid object name: HEAD
listing git files failed - pretending there aren't any
Traceback (most recent call last):
  File "/usr/lib/python3.8/tarfile.py", line 2313, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.8/tarfile.py", line 1103, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib/python3.8/tarfile.py", line 1039, in frombuf
    raise EmptyHeaderError("empty header")
tarfile.EmptyHeaderError: empty header
```

**Comment by tanj** [comment]
Looks like we are getting packages that don't support that version of python.

Works with Python 3.8 on windows, but my tests with 3.6 also had issues.

**Comment by ksamuel** [comment]
This works with poetry though, so I assume it's about filtering the package in a certain way.
