### ISSUE TITLE
Failure to resolve requests

### ISSUE THREAD

**Issue by branchvincent** [David-OConnor/pyflow#139]
Pyflow is unable to resolve the dependencies for the recently-released [requests@2.26.0](https://github.com/psf/requests/releases/tag/v2.26.0):

```console
$ cat << EOF >pyproject.toml
[tool.pyflow]
name = ""
py_version = "3.9"
version = "0.1.0"

[tool.pyflow.dependencies]
requests = "2.26.0"

[tool.pyflow.dev-dependencies]
EOF

$ pyflow install
thread 'main' panicked at 'Can't find a valid version for charset-normalizer', src/dep_resolution.rs:396:40
```

The constraint is [`charset_normalizer~=2.0.0; python_version >= "3"`](https://github.com/psf/requests/blob/a1a6a549a0143d9b32717dbe3d75cd543ae5a4f6/setup.py#L44) (which is new and why this issue is absent with `<2.26.0`.

<details>
    <summary>Stacktrace</summary>
thread 'main' panicked at 'Can't find a valid version for charset-normalizer', src/dep_resolution.rs:396:40
stack backtrace:

```shell
   0:        0x1050eb46e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7dac4b58aa11870a
   1:        0x10512795e - core::fmt::write::h53badd02f711efbe
   2:        0x1050e6cea - std::io::Write::write_fmt::hd02c4bbaf6463567
   3:        0x105104eff - std::panicking::default_hook::{{closure}}::ha7d22468d4529f02
   4:        0x105104a8a - std::panicking::default_hook::hc6c5fb91e7ed228a
   5:        0x105105470 - std::panicking::rust_panic_with_hook::h94fd567d38cd4da7
   6:        0x1050eb7e5 - std::panicking::begin_panic_handler::{{closure}}::h953a8f32e4882703
   7:        0x1050eb5e8 - std::sys_common::backtrace::__rust_end_short_backtrace::h8472811b9ff0c597
   8:        0x105105003 - _rust_begin_unwind
   9:        0x10514423b - std::panicking::begin_panic_fmt::h9c97df342e1c7161
  10:        0x104da5ad2 - pyflow::dep_resolution::res::get_version_info::{{closure}}::hb545d75cbdd8ee35
  11:        0x104da5927 - pyflow::dep_resolution::res::get_version_info::h164e61570e4fbf22
  12:        0x104da667e - pyflow::dep_resolution::res::fetch_req_data::he1e3ae54a315fe0b
  13:        0x104d5324b - pyflow::dep_resolution::guess_graph::h629ca7b25eeb402b
  14:        0x104d53ea7 - pyflow::dep_resolution::guess_graph::h629ca7b25eeb402b
  15:        0x104da85c7 - pyflow::dep_resolution::res::resolve::ha8d660d5714f8d77
  16:        0x104d8b63d - pyflow::sync::hb14bfa7e6e96198f
  17:        0x104d947a4 - pyflow::main::hb5af5a8dc99f5ad6
  18:        0x104dbbd6a - std::sys_common::backtrace::__rust_begin_short_backtrace::h00b61639f172e865
  19:        0x104dbd52c - std::rt::lang_start::{{closure}}::h4ff407d06b350d61
  20:        0x10510e61a - std::rt::lang_start_internal::h43b407d2a4fa0408
  21:        0x104d9b089 - _main
```
</details>

**Comment by clawsl** [comment]
just ran into the same issue on Windows

**Comment by clawsl** [comment]
still had the issue with requests ^2.27.1 and found the following workaround

1. Install charset-normalizer by hand
`pyflow install -d charset-normalizer`

2. Install request again
`pyflow install requests`
 (this time it worked for me)
