### ISSUE TITLE
pyflow fails when creating virtual environment after running `pyflow install` on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by NValsted** [David-OConnor/pyflow#169]
### System info
- Ubuntu 20.04.3 LTS
- pyflow built with --release flag at commit c63e66bae1bbd83fb5fc97921999a19b90664473 (can also be reproduced with release 0.3.1)

### Minimal setup to reproduce
```bash
yes 3.9 | pyflow new /tmp/pyflow_venv_fail
cd /tmp/pyflow_venv_fail
pyflow install
```

### Result
Running the above with `RUST_BACKTRACE=full` yields the following output
```
🐍 Setting up Python...
thread 'main' panicked at 'creating virtual environment: Error: Command '['/tmp/pyflow_venv_fail/__pypackages__/3.9/.venv/bin/python3.9', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
', src/util/mod.rs:784:43
stack backtrace:
   0:     0x55822b7294cc - std::backtrace_rs::backtrace::libunwind::trace::h09f7e4e089375279
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55822b7294cc - std::backtrace_rs::backtrace::trace_unsynchronized::h1ec96f1c7087094e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55822b7294cc - std::sys_common::backtrace::_print_fmt::h317b71fc9a5cf964
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55822b7294cc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55822b750bfc - core::fmt::write::h513b07ca38f4fb1b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
   5:     0x55822b7217d5 - std::io::Write::write_fmt::haf8c932b52111354
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
   6:     0x55822b72b0f0 - std::sys_common::backtrace::_print::h195c38364780a303
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55822b72b0f0 - std::sys_common::backtrace::print::hc09dfdea923b6730
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55822b72b0f0 - std::panicking::default_hook::{{closure}}::hb2e38ec0d91046a3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
   9:     0x55822b72aca5 - std::panicking::default_hook::h60284635b0ad54a8
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
  10:     0x55822b72b7a4 - std::panicking::rust_panic_with_hook::ha677a669fb275654
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17
  11:     0x55822b72b280 - std::panicking::begin_panic_handler::{{closure}}::h976246fb95d93c31
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:502:13
  12:     0x55822b729974 - std::sys_common::backtrace::__rust_end_short_backtrace::h38077ee5b7b9f99a
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55822b72b1e9 - rust_begin_unwind
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
  14:     0x55822b319901 - core::panicking::panic_fmt::h35f3a62252ba0fd2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
  15:     0x55822b409e34 - pyflow::util::check_command_output::{{closure}}::h0561984ad3c615e6
  16:     0x55822b3bb9aa - pyflow::commands::create_venv::h8f67b8eeb43d1976
  17:     0x55822b3ea08f - pyflow::py_versions::create_venv::h5c9602c21174b423
  18:     0x55822b4070e0 - pyflow::util::find_or_create_venv::hc5dd3a17a193f819
  19:     0x55822b3d4497 - pyflow::main::h3b6efbe4b1b9dbe5
  20:     0x55822b385663 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbda9657a7e03de61
  21:     0x55822b3ebcd9 - std::rt::lang_start::{{closure}}::hecda47e4f8292434
  22:     0x55822b72915b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7e688d7cdfeb7e00
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:259:13
  23:     0x55822b72915b - std::panicking::try::do_call::h4be824d2350b44c9
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  24:     0x55822b72915b - std::panicking::try::h0a6fc7affbe5088d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  25:     0x55822b72915b - std::panic::catch_unwind::h22c320f732ec805e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  26:     0x55822b72915b - std::rt::lang_start_internal::{{closure}}::hd38309c108fe679d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:48
  27:     0x55822b72915b - std::panicking::try::do_call::h8fcaf501f097a28e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  28:     0x55822b72915b - std::panicking::try::h20e906825f98acc1
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  29:     0x55822b72915b - std::panic::catch_unwind::h8c5234dc632124ef
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  30:     0x55822b72915b - std::rt::lang_start_internal::hc4dd8cd3ec4518c2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:20
  31:     0x55822b3d9932 - main
  32:     0x7f3a4aea70b3 - __libc_start_main
  33:     0x55822b31a0ae - _start
  34:                0x0 - <unknown>
```

### Workaround
After running `pyflow install` it appears to have created `__pypackages__/3.9/.venv/` succesfully. So when running `pyflow install` a second time, the installation process completes successfully, but naturally this isn't very practical.

**Comment by NValsted** [comment]
Upon further inspection, it seems that `$py_alias -m venv $name` in `src/commands.rs::create_venv` fails because the corresponding `python3.x-venv` package isn't installed along with python. In the above case, manually installing `python3.9-venv` with `apt-get install python3.9-venv` fixes it for me. However, it might make sense to also automatically download and install the corresponding `python3.x-venv` package in `src/py_versions.rs::create_venv` if one doesn't exists.
