### ISSUE TITLE
Failed to install: `manylinux_2_17_aarch64.manylinux2014_aarch64`

### ISSUE THREAD

**Issue by mementum** [David-OConnor/pyflow#172]
OS: Ubuntu 20.04 running in WSL2

Installed with snap
```
snap install pyflow --classic
```

Failure
```
dro@LAPTOP-K91MGR9O:~/tmp/podemium2$ RUST_BACKTRACE=full pyflow install mkdocs-material
🐍 Setting up Python...
⬇ Installing six 1.16.0 ...
⬇ Installing packaging 21.3.0 ...
⬇ Installing importlib_metadata 4.11.2 ...
⬇ Installing pygments 2.11.2 ...
⬇ Installing pyyaml_env_tag 0.1.0 ...
thread 'main' panicked at 'Problem parsing Os: manylinux_2_17_aarch64.manylinux2014_aarch64', src/util.rs:614:53
stack backtrace:
   0:     0x557a460e1e14 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x557a460e1e14 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x557a460e1e14 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x557a460e1e14 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x557a4610a9bc - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x557a460dc387 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x557a460e49be - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x557a460e49be - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x557a460e49be - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x557a460e46b1 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x557a460e50bb - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x557a460e4c5e - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x557a460e4b9f - std::panicking::begin_panic_fmt::ha0f013e3301a9528
                               at src/libstd/panicking.rs:328
  13:     0x557a45cdb39e - pyflow::util::os_from_wheel_fname::{{closure}}::h061c902d51acca7d
  14:     0x557a45cdbcc5 - pyflow::util::find_best_release::hbe17712a91ce6794
  15:     0x557a45d5408c - pyflow::sync::h2ff987914ed32726
  16:     0x557a45d5c4da - pyflow::main::hfa569966dc82e778
  17:     0x557a45c9c543 - std::rt::lang_start::{{closure}}::h29371ddbe7fb2bd0
  18:     0x557a460e4ae3 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  19:     0x557a460e4ae3 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  20:     0x557a460ef15a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  21:     0x557a460e559d - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  22:     0x557a460e559d - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  23:     0x557a460e559d - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  24:     0x557a45d63492 - main
  25:     0x7f14e0819bf7 - __libc_start_main
  26:     0x557a45c8829a - _start
  27:                0x0 - <unknown>
```

**Comment by barakplasma** [comment]
also happens for me running the snap (pyflow 0.2.4) on Ubuntu 21.10
`thread 'main' panicked at 'Problem parsing Os: manylinux2014_aarch64', src/util.rs:614:53`
I think it's referring to the last released version, and not necessarily the latest version in master. The last release would be referring to https://github.com/David-OConnor/pyflow/blob/6fa61ab558a13c26c72bfc33b6bdf30f56dcac27/src/util.rs#L79 

I'll try again on latest version to see if it happens there too
