### ISSUE TITLE
Cannot `pyflow install black`

### ISSUE THREAD

**Issue by braincore** [David-OConnor/pyflow#73]
Giving `pyflow` a spin for the first time and this came up:

```
$ RUST_BACKTRACE=full pyflow install black
Found lockfile
⬇ Installing appdirs 1.4.4 ...
⬇ Installing regex 2020.6.8 ...
⬇ Installing attrs 19.3.0 ...
⬇ Installing click 7.1.2 ...
⬇ Installing toml 0.10.1 ...
⬇ Installing black 19.10.0b0 ...
EX PAR: "__pypackages__/3.8/lib/black-19.10b0" bin: "__pypackages__/3.8/.venv/bin"
thread 'main' panicked at 'Problem running setup.py bdist_wheel: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55da42d39e14 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55da42d39e14 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55da42d39e14 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55da42d39e14 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55da42d629bc - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x55da42d34387 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x55da42d3c9be - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55da42d3c9be - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55da42d3c9be - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x55da42d3c6b1 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x55da42d3d0bb - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x55da42d3cc5e - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x55da42d3cb46 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  13:     0x55da42d5f58e - core::panicking::panic_fmt::hdeb7979ab6591473
                               at src/libcore/panicking.rs:139
  14:     0x55da42d5f687 - core::result::unwrap_failed::h054dd680e6fcd38b
                               at src/libcore/result.rs:1165
  15:     0x55da429d0a2c - pyflow::install::download_and_install_package::h8e64a7e68ee71a6a
  16:     0x55da429ac1b5 - pyflow::sync::h2ff987914ed32726
  17:     0x55da429b6ced - pyflow::main::hfa569966dc82e778
  18:     0x55da428f4543 - std::rt::lang_start::{{closure}}::h29371ddbe7fb2bd0
  19:     0x55da42d3cae3 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  20:     0x55da42d3cae3 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  21:     0x55da42d4715a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  22:     0x55da42d3d59d - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  23:     0x55da42d3d59d - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  24:     0x55da42d3d59d - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  25:     0x55da429bb492 - main
  26:     0x7f671ea21b97 - __libc_start_main
  27:     0x55da428e029a - _start
  28:                0x0 - <unknown>
```

Installing other packages such as `requests` worked without a hitch.

**Comment by David-OConnor** [comment]
What OS? Is this using a system Python, or one installed by pyflow?

**Comment by braincore** [comment]
Ubuntu 18.04 using system Python 3.6.9.

**Comment by David-OConnor** [comment]
Does it work if you use `python3.6` in pyproject.toml?

**Comment by braincore** [comment]
Yes, that did the trick. So pyflow won't pull in an arbitrary Python version that I've specified in pyproject.toml?

**Comment by David-OConnor** [comment]
It will - but there's evidently a bug going on here. That was a diagnostic step, not a fix.

**Comment by braincore** [comment]
Great, I think that's the right approach. Do you know what Poetry's reasoning is for not vendorizing a specific Python version?

**Comment by David-OConnor** [comment]
I believe it's considered out of scope: Poetry is, philosophically, a package manager, not a Python manager. One of my initial motivations for this project was to include in the scope anything that would streamline the Python workflow.

**Comment by braincore** [comment]
Off topic from this thread, but how much time are you putting into this? How many hours do you think you need to get the project to a robust state? Wish I had the time to contribute as I think a project like this is sorely needed especially after spending time in the rust & js ecosystems.

**Comment by David-OConnor** [comment]
I'm putting in very little time - cleaning up the easy things, but it's on the backburner. Put a lot of time into it about a year ago when starting.

I think the biggest area to focus on is making it work for any resolvable dependency tree without failing. Ie, eliminate issues like this. I think a good chunk of them would go away by fixing the issue I spoke of. In other words, packaging standalone Python binaries that have all the extras, instead of the sparse ones the default compile steps give you.

**Comment by David-OConnor** [comment]
I released a fix to the binary dep that should fix this on Windows. Will attempt an equiv for Linux if the Windows fix works for everyone.
