### ISSUE TITLE
Windows 10 was misrecognized as "manylinux2014_aarch64" in Powershell

### ISSUE THREAD

**Issue by luckynum7** [David-OConnor/pyflow#85]
- OS: Windows 10 Professional
- Shell: Powershell 5.1, Powershell Core 7.0.3
- Python: not installed
- pyflow: 0.2.7 (installed in scoop)
- `pyflow --version`: `pyflow 0.2.6`
- `scoop list pyflow`: `pyflow 0.2.7`

<details><summary>pyproject.toml:</summary>

```pyproject.toml
# See PEP 518: https://www.python.org/dev/peps/pep-0518/ for info on this file's structure.

[tool.pyflow]
name = ""
py_version = "3.8"
version = "0.5.0"

# [tool.pyflow.scripts]

[tool.pyflow.dependencies]
ahk = "0.9.0"
numpy = "1.19.1"
openpyxl = "3.0.5"
pandas = "1.1.1"
requests = "2.24.0"
roman = "3.3.0"

[tool.pyflow.dev-dependencies]
pytest = "6.0.1"
```
</details>

- Commands (after `pyflow clear; pyflow reset`):
```powershell
$env:RUST_BACKTRACE="full"
pyflow
```

- Error message:

```powershell
thread 'main' panicked at 'Problem parsing Os: manylinux2014_aarch64', src\util.rs:643:53
```

and
```powershell
thread 'main' panicked at 'Problem parsing constraint from requires_python: DependencyError { details: "Problem parsing version: " }', src\util.rs:671:38
```

<details><summary>Outputs (Powershell 5.1):</summary>

```powershell
Downloading Python 3.8.0...
Installing Python 3.8.0...
Setting up Python...
Installing chardet 3.0.4 ...
Added a console script: chardetect
Installing jdcal 1.4.1 ...
Installing pytest 6.0.1 ...
Added a console script: py.test
Added a console script: pytest
Installing atomicwrites 1.4.0 ...
Installing py 1.9.0 ...
Installing pandas 1.1.1 ...
Installing toml 0.10.1 ...
Installing pluggy 0.13.1 ...
thread 'main' panicked at 'Problem parsing Os: manylinux2014_aarch64', src\util.rs:643:53
stack backtrace:
   0:     0x7ff62664e69f - <unknown>
   1:     0x7ff62666eecb - <unknown>
   2:     0x7ff626644a3c - <unknown>
   3:     0x7ff626651aac - <unknown>
   4:     0x7ff6266516ef - <unknown>
   5:     0x7ff626652297 - <unknown>
   6:     0x7ff626651e1f - <unknown>
   7:     0x7ff626651d8c - <unknown>
   8:     0x7ff6262490d0 - <unknown>
   9:     0x7ff626249a65 - <unknown>
  10:     0x7ff626284872 - <unknown>
  11:     0x7ff62628ed72 - <unknown>
  12:     0x7ff626252676 - <unknown>
  13:     0x7ff6266524bf - <unknown>
  14:     0x7ff62629edb7 - <unknown>
  15:     0x7ff626692624 - <unknown>
  16:     0x7ff9ce036fd4 - BaseThreadInitThunk
  17:     0x7ff9ce21cec1 - RtlUserThreadStart
```

</details>

<details><summary>Outputs (Powershell 7.0.3):</summary>

```powershell
Downloading Python 3.8.0...
Installing Python 3.8.0...
Setting up Python...
Installing toml 0.10.1 ...
Installing packaging 20.4.0 ...
Installing six 1.15.0 ...
Installing pyparsing 2.4.7 ...
thread 'main' panicked at 'Problem parsing Os: manylinux2014_aarch64', src\util.rs:643:53
stack backtrace:
   0:     0x7ff62664e69f - <unknown>
   1:     0x7ff62666eecb - <unknown>
   2:     0x7ff626644a3c - <unknown>
   3:     0x7ff626651aac - <unknown>
   4:     0x7ff6266516ef - <unknown>
   5:     0x7ff626652297 - <unknown>
   6:     0x7ff626651e1f - <unknown>
   7:     0x7ff626651d8c - <unknown>
   8:     0x7ff6262490d0 - <unknown>
   9:     0x7ff626249a65 - <unknown>
  10:     0x7ff626284872 - <unknown>
  11:     0x7ff62628ed72 - <unknown>
  12:     0x7ff626252676 - <unknown>
  13:     0x7ff6266524bf - <unknown>
  14:     0x7ff62629edb7 - <unknown>
  15:     0x7ff626692624 - <unknown>
  16:     0x7ff9ce036fd4 - BaseThreadInitThunk
  17:     0x7ff9ce21cec1 - RtlUserThreadStart
```
</details>

<details><summary>After run `pyflow` over and over against the project:</summary>

```powershell
Installing pytz 2020.1.0 ...
Installing jdcal 1.4.1 ...
Installing pandas 1.1.1 ...
Installing et_xmlfile 1.0.1 ...
Installing jinja2 2.11.2 ...
Installing colorama 0.4.3 ...
Installing atomicwrites 1.4.0 ...
Installing python_dateutil 2.8.1 ...
Installing markupsafe 1.1.1 ...
Installing idna 2.10.0 ...
Installing pluggy 0.13.1 ...
thread 'main' panicked at 'Problem parsing Os: manylinux2014_aarch64', src\util.rs:643:53
stack backtrace:
   0:     0x7ff62664e69f - <unknown>
   1:     0x7ff62666eecb - <unknown>
   2:     0x7ff626644a3c - <unknown>
   3:     0x7ff626651aac - <unknown>
   4:     0x7ff6266516ef - <unknown>
   5:     0x7ff626652297 - <unknown>
   6:     0x7ff626651e1f - <unknown>
   7:     0x7ff626651d8c - <unknown>
   8:     0x7ff6262490d0 - <unknown>
   9:     0x7ff626249a65 - <unknown>
  10:     0x7ff626284872 - <unknown>
  11:     0x7ff62628ed72 - <unknown>
  12:     0x7ff626252676 - <unknown>
  13:     0x7ff6266524bf - <unknown>
  14:     0x7ff62629edb7 - <unknown>
  15:     0x7ff626692624 - <unknown>
  16:     0x7ff9ce036fd4 - BaseThreadInitThunk
  17:     0x7ff9ce21cec1 - RtlUserThreadStart

Installing more_itertools 8.4.0 ...
Installing py 1.9.0 ...
Installing certifi 2020.6.20 ...
thread 'main' panicked at 'Problem parsing Os: manylinux2014_aarch64', src\util.rs:643:53
stack backtrace:
   0:     0x7ff62664e69f - <unknown>
   1:     0x7ff62666eecb - <unknown>
   2:     0x7ff626644a3c - <unknown>
   3:     0x7ff626651aac - <unknown>
   4:     0x7ff6266516ef - <unknown>
   5:     0x7ff626652297 - <unknown>
   6:     0x7ff626651e1f - <unknown>
   7:     0x7ff626651d8c - <unknown>
   8:     0x7ff6262490d0 - <unknown>
   9:     0x7ff626249a65 - <unknown>
  10:     0x7ff626284872 - <unknown>
  11:     0x7ff62628ed72 - <unknown>
  12:     0x7ff626252676 - <unknown>
  13:     0x7ff6266524bf - <unknown>
  14:     0x7ff62629edb7 - <unknown>
  15:     0x7ff626692624 - <unknown>
  16:     0x7ff9ce036fd4 - BaseThreadInitThunk
  17:     0x7ff9ce21cec1 - RtlUserThreadStart

Installing urllib3 1.25.10 ...
thread 'main' panicked at 'Problem parsing constraint from requires_python: DependencyError { details: "Problem parsing version: " }', src\util.rs:671:38
stack backtrace:
   0:     0x7ff62664e69f - <unknown>
   1:     0x7ff62666eecb - <unknown>
   2:     0x7ff626644a3c - <unknown>
   3:     0x7ff626651aac - <unknown>
   4:     0x7ff6266516ef - <unknown>
   5:     0x7ff626652297 - <unknown>
   6:     0x7ff626651e1f - <unknown>
   7:     0x7ff62666d810 - <unknown>
   8:     0x7ff62666d643 - <unknown>
   9:     0x7ff626249b42 - <unknown>
  10:     0x7ff626284872 - <unknown>
  11:     0x7ff62628ed72 - <unknown>
  12:     0x7ff626252676 - <unknown>
  13:     0x7ff6266524bf - <unknown>
  14:     0x7ff62629edb7 - <unknown>
  15:     0x7ff626692624 - <unknown>
  16:     0x7ff9ce036fd4 - BaseThreadInitThunk
  17:     0x7ff9ce21cec1 - RtlUserThreadStart

Installing roman 3.3.0 ...
Added a console script: roman
Installing attrs 20.1.0 ...
thread 'main' panicked at 'Problem parsing Os: manylinux2014_aarch64', src\util.rs:643:53
stack backtrace:
   0:     0x7ff62664e69f - <unknown>
   1:     0x7ff62666eecb - <unknown>
   2:     0x7ff626644a3c - <unknown>
   3:     0x7ff626651aac - <unknown>
   4:     0x7ff6266516ef - <unknown>
   5:     0x7ff626652297 - <unknown>
   6:     0x7ff626651e1f - <unknown>
   7:     0x7ff626651d8c - <unknown>
   8:     0x7ff6262490d0 - <unknown>
   9:     0x7ff626249a65 - <unknown>
  10:     0x7ff626284872 - <unknown>
  11:     0x7ff62628ed72 - <unknown>
  12:     0x7ff626252676 - <unknown>
  13:     0x7ff6266524bf - <unknown>
  14:     0x7ff62629edb7 - <unknown>
  15:     0x7ff626692624 - <unknown>
  16:     0x7ff9ce036fd4 - BaseThreadInitThunk
  17:     0x7ff9ce21cec1 - RtlUserThreadStart

thread 'main' panicked at 'Problem parsing constraint from requires_python: DependencyError { details: "Problem parsing version: " }', src\util.rs:671:38
stack backtrace:
   0:     0x7ff62664e69f - <unknown>
   1:     0x7ff62666eecb - <unknown>
   2:     0x7ff626644a3c - <unknown>
   3:     0x7ff626651aac - <unknown>
   4:     0x7ff6266516ef - <unknown>
   5:     0x7ff626652297 - <unknown>
   6:     0x7ff626651e1f - <unknown>
   7:     0x7ff62666d810 - <unknown>
   8:     0x7ff62666d643 - <unknown>
   9:     0x7ff626249b42 - <unknown>
  10:     0x7ff626284872 - <unknown>
  11:     0x7ff62628ed72 - <unknown>
  12:     0x7ff626252676 - <unknown>
  13:     0x7ff6266524bf - <unknown>
  14:     0x7ff62629edb7 - <unknown>
  15:     0x7ff626692624 - <unknown>
  16:     0x7ff9ce036fd4 - BaseThreadInitThunk
  17:     0x7ff9ce21cec1 - RtlUserThreadStart

Installing chardet 3.0.4 ...
Added a console script: chardetect
thread 'main' panicked at 'Problem parsing constraint from requires_python: DependencyError { details: "Problem parsing version: " }', src\util.rs:671:38
stack backtrace:
   0:     0x7ff62664e69f - <unknown>
   1:     0x7ff62666eecb - <unknown>
   2:     0x7ff626644a3c - <unknown>
   3:     0x7ff626651aac - <unknown>
   4:     0x7ff6266516ef - <unknown>
   5:     0x7ff626652297 - <unknown>
   6:     0x7ff626651e1f - <unknown>
   7:     0x7ff62666d810 - <unknown>
   8:     0x7ff62666d643 - <unknown>
   9:     0x7ff626249b42 - <unknown>
  10:     0x7ff626284872 - <unknown>
  11:     0x7ff62628ed72 - <unknown>
  12:     0x7ff626252676 - <unknown>
  13:     0x7ff6266524bf - <unknown>
  14:     0x7ff62629edb7 - <unknown>
  15:     0x7ff626692624 - <unknown>
  16:     0x7ff9ce036fd4 - BaseThreadInitThunk
  17:     0x7ff9ce21cec1 - RtlUserThreadStart

thread 'main' panicked at 'Problem parsing Os: manylinux2014_aarch64', src\util.rs:643:53
stack backtrace:
   0:     0x7ff62664e69f - <unknown>
   1:     0x7ff62666eecb - <unknown>
   2:     0x7ff626644a3c - <unknown>
   3:     0x7ff626651aac - <unknown>
   4:     0x7ff6266516ef - <unknown>
   5:     0x7ff626652297 - <unknown>
   6:     0x7ff626651e1f - <unknown>
   7:     0x7ff626651d8c - <unknown>
   8:     0x7ff6262490d0 - <unknown>
   9:     0x7ff626249a65 - <unknown>
  10:     0x7ff626284872 - <unknown>
  11:     0x7ff62628ed72 - <unknown>
  12:     0x7ff626252676 - <unknown>
  13:     0x7ff6266524bf - <unknown>
  14:     0x7ff62629edb7 - <unknown>
  15:     0x7ff626692624 - <unknown>
  16:     0x7ff9ce036fd4 - BaseThreadInitThunk
  17:     0x7ff9ce21cec1 - RtlUserThreadStart

thread 'main' panicked at 'Problem parsing constraint from requires_python: DependencyError { details: "Problem parsing version: " }', src\util.rs:671:38
stack backtrace:
   0:     0x7ff62664e69f - <unknown>
   1:     0x7ff62666eecb - <unknown>
   2:     0x7ff626644a3c - <unknown>
   3:     0x7ff626651aac - <unknown>
   4:     0x7ff6266516ef - <unknown>
   5:     0x7ff626652297 - <unknown>
   6:     0x7ff626651e1f - <unknown>
   7:     0x7ff62666d810 - <unknown>
   8:     0x7ff62666d643 - <unknown>
   9:     0x7ff626249b42 - <unknown>
  10:     0x7ff626284872 - <unknown>
  11:     0x7ff62628ed72 - <unknown>
  12:     0x7ff626252676 - <unknown>
  13:     0x7ff6266524bf - <unknown>
  14:     0x7ff62629edb7 - <unknown>
  15:     0x7ff626692624 - <unknown>
  16:     0x7ff9ce036fd4 - BaseThreadInitThunk
  17:     0x7ff9ce21cec1 - RtlUserThreadStart

thread 'main' panicked at 'Problem parsing Os: manylinux2014_aarch64', src\util.rs:643:53
stack backtrace:
   0:     0x7ff62664e69f - <unknown>
   1:     0x7ff62666eecb - <unknown>
   2:     0x7ff626644a3c - <unknown>
   3:     0x7ff626651aac - <unknown>
   4:     0x7ff6266516ef - <unknown>
   5:     0x7ff626652297 - <unknown>
   6:     0x7ff626651e1f - <unknown>
   7:     0x7ff626651d8c - <unknown>
   8:     0x7ff6262490d0 - <unknown>
   9:     0x7ff626249a65 - <unknown>
  10:     0x7ff626284872 - <unknown>
  11:     0x7ff62628ed72 - <unknown>
  12:     0x7ff626252676 - <unknown>
  13:     0x7ff6266524bf - <unknown>
  14:     0x7ff62629edb7 - <unknown>
  15:     0x7ff626692624 - <unknown>
  16:     0x7ff9ce036fd4 - BaseThreadInitThunk
  17:     0x7ff9ce21cec1 - RtlUserThreadStart
```
</details>

**Comment by David-OConnor** [comment]
This is due to the dep listing that architecture. The patch is easy (I'll do it soon), but the broader fix is not making it crash when it sees one it doesn't recognize.

**Comment by David-OConnor** [comment]
Actually... I think this is already fixed in the repo, but hasn't been released.

**Comment by David-OConnor** [comment]
Released. Update to 0.2.8 and try again.

**Comment by luckynum7** [comment]
Same pyproject.toml, after `pyflow clear; pyflow reset`:

```powershell
thread 'main' panicked at 'Problem parsing constraint from requires_python: DependencyError { details: "Problem parsing constraint: " }', src\util.rs:673:26
```

<details><summary>Outputs (Powershell 5.1):</summary>

```powershell
$ pyflow --version
pyflow 0.2.8

$ pyflow
Found multiple compatible Python versions. Please enter the number associated with the one you'd like to use:
1: python3: 3.8.5
2: python: 3.8.5 
2
Setting up Python...
Installing py 1.9.0 ...
Installing requests 2.24.0 ...
Installing pytest 6.0.1 ...
Added a console script: py.test
Added a console script: pytest
Installing toml 0.10.1 ...
Installing iniconfig 1.0.1 ...
Installing atomicwrites 1.4.0 ...
Installing numpy 1.19.1 ...
Added a console script: f2py
Installing pluggy 0.13.1 ...
Installing markupsafe 1.1.1 ...
Installing jinja2 2.11.2 ...
Installing pytz 2020.1.0 ...
Installing certifi 2020.6.20 ...
Installing urllib3 1.25.10 ...
Installing chardet 3.0.4 ...
Added a console script: chardetect
Installing ahk 0.9.0 ...
Installing roman 3.3.0 ...
Added a console script: roman
Installing et_xmlfile 1.0.1 ...
Installing python_dateutil 2.8.1 ...
thread 'main' panicked at 'Problem parsing constraint from requires_python: DependencyError { details: "Problem parsing constraint: " }', src\util.rs:673:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

</details>

**Comment by David-OConnor** [comment]
I believe this is now fixed.
