### ISSUE TITLE
Manjaro KDE recognized as "manylinux2014_ppc64le".

### ISSUE THREAD

**Issue by elskito** [David-OConnor/pyflow#99]
Please enter the number corresponding to your Linux distro:
1: 2016 or newer (Ubuntu≥16.04, Debian≥9, SUSE≥15, Arch, Kali, etc)
2: Older (Centos, Redhat, Fedora, older versions of distros listed in option 1)
1
Downloading Python 3.8.0...
Installing Python 3.8.0...
🐍 Setting up Python...
⬇ Installing cycler 0.10.0 ...
⬇ Installing six 1.15.0 ...
⬇ Installing pyparsing 2.4.7 ...
⬇ Installing itsdangerous 1.1.0 ...
⬇ Installing python_dateutil 2.8.1 ...
⬇ Installing pillow 8.1.0 ...
⬇ Installing click 7.1.2 ...
⬇ Installing flask_login 0.5.0 ...
⬇ Installing werkzeug 1.0.1 ...
thread 'main' panicked at 'Problem parsing Os: manylinux2014_ppc64le', src/util.rs:643:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Problem exists both when pyflow installed via pip and when binary copied to /usr/bin.

**Comment by David-OConnor** [comment]
This is similar to previous issues I've applied bandaids to. It's actually just freaking out about not recognizing that OS in a dependency. I'll leave this open until fully addressed.

**Comment by elskito** [comment]
I found out that when installing pyflow via Rust (cargo install pyflow) system is correctly recognized.

**Comment by David-OConnor** [comment]
How were you installing before - the installer?

**Comment by elskito** [comment]
As I said in first post I used:

- A different Linux distro - Download this standalone binary and place it somewhere accessible by the PATH. For example, /usr/bin.
- With Pip - Run pip install pyflow. The linux install using this method is much larger than with the above ones, and it doesn't yet work with Mac. This method will likely not work with Red Hat, CentOs, or Fedora.

In both the problem was the same. The only solution for me was to use this "cargo" approach. ;)

**Comment by 275RR** [comment]
similar issue on PopOS (debian) using .deb install method:

self@pc:/media/self/backup/Code/PROJECTS/test$ pyflow init
Please enter the Python version for this project: (eg: 3.8)
3.8
Created `pyproject.toml`
Found multiple compatible Python versions. Please enter the number associated with the one you'd like to use:
1: python3.8: 3.8.6
2: python3: 3.8.6
1
🐍 Setting up Python...
⬇ Installing wrapt 1.11.2 ...
⬇ Installing requests 2.25.1 ...
⬇ Installing mccabe 0.6.1 ...
⬇ Installing certifi 2020.12.5 ...
⬇ Installing attrs 20.3.0 ...
⬇ Installing urllib3 1.26.3 ...
⬇ Installing toml 0.10.2 ...
⬇ Installing chardet 3.0.4 ...
Added a console script: chardetect
⬇ Installing pylint 2.6.0 ...
Added a console script: epylint
Added a console script: pylint
Added a console script: pyreverse
Added a console script: symilar
⬇ Installing isort 5.7.0 ...
Added a console script: isort
Added a console script: isort-identify-imports
⬇ Installing idna 2.10.0 ...
⬇ Installing six 1.12.0 ...
⬇ Installing async_timeout 3.0.1 ...
thread 'main' panicked at 'Problem parsing Os: manylinux2014_ppc64le', src/util.rs:643:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by elskito** [comment]
@David-OConnor I discovered that my problem is with choosing python 3.6 when pyflow asking. When I choose 3.8 or 3.9 an evironment is setting up correctly.
